### PR TITLE
Fix connection error handlers

### LINKED ISSUE #214: Producer send failure doesn't set connection as failing
During a producer's send call, if the connection fails to send the message, the error management doesn't set the connection as failing at this line:

https://github.com/streamnative/pulsar-rs/blob/c31fc8335e4e321c85e0024aa4189c318a581082/src/producer.rs#L721

And the in the else case of this line:
https://github.com/streamnative/pulsar-rs/blob/c31fc8335e4e321c85e0024aa4189c318a581082/src/producer.rs#L723

So the reconnect call will use the same failing connection:

https://github.com/streamnative/pulsar-rs/blob/c31fc8335e4e321c85e0024aa4189c318a581082/src/producer.rs#L738 

That being said, you'll guess that the connection_manager ping will send_ping and put the connection as failing. But I think if we run a cluster with a pulsar proxy, the pulsar proxy will answer pong and not the failing broker.

Please note that the last sentence is a pure suggestion. I'm investigating a very difficult reproducible case of stuck pulsar-rs during pulsar producing. This can be related to https://github.com/streamnative/pulsar-rs/issues/212 or race conditions of both issues. Don't know yet.

### PR DESCRIPTION
**Pull request by KannarFr**
Closes https://github.com/streamnative/pulsar-rs/issues/214. But based on https://github.com/streamnative/pulsar-rs/pull/216.

Not fixed, but better information:

Using a broker that never responds to `handleSend` messages in order to trigger timeout on the client's side. And running the `round_trip`:

I get

```
2022-06-20 14:04:09.167886395 UTC  DEBUG        pulsar::connection_manager      ConnectionManager::connect(BrokerAddress { url: Url { scheme: "pulsar", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("127.0.0.1")), port: Some(6650), path: "", query: None, fragment: None }, broker_url: "127.0.0
.1:6650", proxy: false })                                                      
2022-06-20 14:04:09.168203314 UTC  DEBUG        pulsar::connection      Connecting to pulsar://127.0.0.1:6650: 127.0.0.1:6650                                                                                                                                                                                                  
2022-06-20 14:04:09.169212514 UTC  INFO pulsar::connection_manager      Connected n°-1498647850098426708 to pulsar://127.0.0.1:6650 in 1ms                                                                                                                                                                                     
2022-06-20 14:04:09.174852628 UTC  DEBUG        pulsar::connection_manager      ConnectionManager::connect(BrokerAddress { url: Url { scheme: "pulsar", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("127.0.0.1")), port: Some(6650), path: "", query: None, fragment: None }, broker_url: "localho
st:6650", proxy: true })                                                                                                                                       
2022-06-20 14:04:09.174979977 UTC  DEBUG        pulsar::connection      Connecting to pulsar://127.0.0.1:6650: 127.0.0.1:6650                                                                                                                                                                                                  
2022-06-20 14:04:09.175861348 UTC  INFO pulsar::connection_manager      Connected n°671655203122723910 to localhost:6650 via proxy pulsar://127.0.0.1:6650 in 0ms                                                                                                                                                              
2022-06-20 14:04:09.228102904 UTC  INFO pulsar::tests   producer created                                                                                       
2022-06-20 14:04:09.228370575 UTC  INFO pulsar::tests   will send message                                                                                      
2022-06-20 14:04:14.229866885 UTC  WARN pulsar::connection      timeout sending message to the Pulsar server                                                                                                                                                                                                                   
2022-06-20 14:04:14.229960438 UTC  WARN pulsar::producer        set connection failing with Timeout                                                            
2022-06-20 14:04:14.230019880 UTC  ERROR        pulsar::producer        send_inner: connection 671655203122723910 disconnected                                                                                                                                                                                                 
2022-06-20 14:04:14.232225958 UTC  DEBUG        pulsar::connection_manager      ConnectionManager::connect(BrokerAddress { url: Url { scheme: "pulsar", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("127.0.0.1")), port: Some(6650), path: "", query: None, fragment: None }, broker_url: "localho
st:6650", proxy: true })                                                       
2022-06-20 14:04:14.232710937 UTC  DEBUG        pulsar::connection      Connecting to pulsar://127.0.0.1:6650: 127.0.0.1:6650                                                                                                                                                                                                  
2022-06-20 14:04:14.235752054 UTC  INFO pulsar::connection_manager      Connected n°-2079755032641021880 to localhost:6650 via proxy pulsar://127.0.0.1:6650 in 3ms                                                                                                                                                            
2022-06-20 14:04:14.235948481 UTC  WARN pulsar::producer        Retry #0 -> reconnecting producer 11864658257378581019 using connection -2079755032641021880 to broker pulsar://127.0.0.1:6650 to topic test_31704                                                                                                             
2022-06-20 14:04:14.238421810 UTC  ERROR        pulsar::producer        TopicProducer::from_connection error[824]: PulsarError(Some(ProducerBusy), Some("org.apache.pulsar.broker.service.BrokerServiceException$NamingException: Producer with name 'standalone-0-39' is already connected to topic"))                        
2022-06-20 14:04:14.238538923 UTC  WARN pulsar::producer        create_producer(test_31704) answered ProducerBusy, retrying request after 15000ms (max_retries = None): org.apache.pulsar.broker.service.BrokerServiceException$NamingException: Producer with name 'standalone-0-39' is already connected to topic
2022-06-20 14:04:29.240694096 UTC  DEBUG        pulsar::connection_manager      ConnectionManager::connect(BrokerAddress { url: Url { scheme: "pulsar", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("127.0.0.1")), port: Some(6650), path: "", query: None, fragment: None }, broker_url: "127.0.0
.1:6650", proxy: false })                                                                                                                                      
2022-06-20 14:04:29.241627023 UTC  DEBUG        pulsar::connection      Connecting to pulsar://127.0.0.1:6650: 127.0.0.1:6650                                                                                                                                                                                                  
2022-06-20 14:04:29.245784677 UTC  INFO pulsar::connection_manager      Connected n°2819212208112083275 to pulsar://127.0.0.1:6650 in 4ms                                                                                                                                                                                      
2022-06-20 14:04:29.248246600 UTC  WARN pulsar::producer        Retry #1 -> reconnecting producer 11864658257378581019 using connection -2079755032641021880 to broker pulsar://127.0.0.1:6650 to topic test_31704                                                                                                             
2022-06-20 14:04:29.250873017 UTC  ERROR        pulsar::producer        TopicProducer::from_connection error[824]: PulsarError(Some(ProducerBusy), Some("org.apache.pulsar.broker.service.BrokerServiceException$NamingException: Producer with name 'standalone-0-39' is already connected to topic"))                        
2022-06-20 14:04:29.250955631 UTC  WARN pulsar::producer        create_producer(test_31704) answered ProducerBusy, retrying request after 15000ms (max_retries = None): org.apache.pulsar.broker.service.BrokerServiceException$NamingException: Producer with name 'standalone-0-39' is already connected to topic
2022-06-20 14:04:44.254643743 UTC  WARN pulsar::producer        Retry #2 -> reconnecting producer 11864658257378581019 using connection -2079755032641021880 to broker pulsar://127.0.0.1:6650 to topic test_31704                                                                                                             
2022-06-20 14:04:44.277827897 UTC  ERROR        pulsar::producer        TopicProducer::from_connection error[824]: PulsarError(Some(ProducerBusy), Some("org.apache.pulsar.broker.service.BrokerServiceException$NamingException: Producer with name 'standalone-0-39' is already connected to topic"))                        
2022-06-20 14:04:44.277904791 UTC  WARN pulsar::producer        create_producer(test_31704) answered ProducerBusy, retrying request after 15000ms (max_retries = None): org.apache.pulsar.broker.service.BrokerServiceException$NamingException: Producer with name 'standalone-0-39' is already connected to topic
2022-06-20 14:04:59.278871712 UTC  DEBUG        pulsar::connection_manager      ConnectionManager::connect(BrokerAddress { url: Url { scheme: "pulsar", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("127.0.0.1")), port: Some(6650), path: "", query: None, fragment: None }, broker_url: "127.0.0
.1:6650", proxy: false })
```

To it seems the producer is held on an unreleased connection. Using `lsof -i :6650` we can see one port not cleaned; I don't understand why.

You can easily reproduce by running `test_round` test using

```bash
cargo test round_trip -- --nocapture
```

On a pulsar standalone patched with

```git
From 57348b0e8d81ee9554744202214c3c713f9881f2 Mon Sep 17 00:00:00 2001
From: "Alexandre DUVAL - @kannarfr" <kannarfr@gmail.com>
Date: Mon, 20 Jun 2022 16:13:42 +0200
Subject: [PATCH] make handleSend timeout

---
 .../java/org/apache/pulsar/common/protocol/PulsarDecoder.java | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarDecoder.java b/pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarDecoder.java
index ecf837b536..7d13623617 100644
--- a/pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarDecoder.java
+++ b/pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarDecoder.java
@@ -203,8 +203,8 @@ public abstract class PulsarDecoder extends ChannelInboundHandlerAdapter {
                 try {
                     interceptCommand(cmd);
                     // Store a buffer marking the content + headers
-                    ByteBuf headersAndPayload = buffer.markReaderIndex();
-                    handleSend(cmd.getSend(), headersAndPayload);
+                    //ByteBuf headersAndPayload = buffer.markReaderIndex();
+                    //handleSend(cmd.getSend(), headersAndPayload);
                 } catch (InterceptException e) {
                     ctx.writeAndFlush(Commands.newSendError(cmd.getSend().getProducerId(),
                             cmd.getSend().getSequenceId(), getServerError(e.getErrorCode()), e.getMessage()));
-- 
2.36.1
```

### CODE REVIEW

**Comment by KannarFr** [comment]
It looks like we should move the https://github.com/streamnative/pulsar-rs/blob/master/src/producer.rs#L830 somewhere in the loop to drop the failing connection.

**Comment by KannarFr** [comment]
Should be fixing the issues.

File: src/producer.rs [hunk 1]
```diff
@@ -710,54 +738,55 @@ impl<Exe: Executor> TopicProducer<Exe> {
...
+                self.connection.id()
+            );
+
+            self.reconnect().await?;
         }
     }
 
     async fn reconnect(&mut self) -> Result<(), Error> {
         debug!("reconnecting producer for topic: {}", self.topic);
+        let (_drop_signal, _) = oneshot::channel::<()>();
```
Comment (FlorentinDUBOIS) [inline src/producer.rs]: You can remove the underscore as prefix of `drop_signal`, as you use it below

**Comment by KannarFr** [comment]
@DonghunLouisLee @freeznet It seems to fix some stuff but still not production ready apparently. Can you have a look?

Also, since I fixed the connection drop before reconnect in the producer, ProducerBusy retry seems useless.

**Comment by KannarFr** [comment]
@DonghunLouisLee @freeznet can you give me feedbacks?

**Review by FlorentinDUBOIS — CHANGES_REQUESTED** [review]
A few change, but the main modification is good :)

File: src/client.rs [hunk 2]
```diff
@@ -555,9 +562,27 @@ async fn run_producer<Exe: Executor>(
...
-            Ok(future) => {
+            Ok(send_f) => {
+                let delay_f = client
+                    .executor
+                    .delay(client.operation_retry_options.operation_timeout);
+
                 let _ = client.executor.spawn(Box::pin(async move {
-                    let _ = resolver.send(future.await);
+                    pin_mut!(delay_f);
+                    pin_mut!(send_f);
```
Comment (DonghunLouisLee) [inline src/client.rs]: https://github.com/streamnative/pulsar-rs/pull/216#discussion_r950642407

File: src/connection.rs [hunk 3]
```diff
@@ -695,8 +720,10 @@ impl<Exe: Executor> Connection<Exe> {
 
         let hostname = hostname.unwrap_or_else(|| address.ip().to_string());
 
-        debug!("Connecting to {}: {}", url, address);
+        let id = rand::random();
```
Comment (DonghunLouisLee) [inline src/connection.rs]: I think rand::random is fine since there wouldn't be a hugh chance of generating same number but it would be idea if we could leave a comment for possbile random number conflict!

File: src/connection.rs [hunk 4]
```diff
@@ -265,6 +266,7 @@ pub struct ConnectionSender<Exe: Executor> {
 
 impl<Exe: Executor> ConnectionSender<Exe> {
     pub(crate) fn new(
+        connection_id: i64,
```
Comment (DonghunLouisLee) [inline src/connection.rs]: Just a minor recommendation: connection id could be u64 for clarirty?

File: src/connection_manager.rs [hunk 5]
```diff
@@ -64,7 +64,7 @@ impl std::default::Default for OperationRetryOptions {
     fn default() -> Self {
         OperationRetryOptions {
             operation_timeout: Duration::from_secs(30),
-            retry_delay: Duration::from_millis(500),
+            retry_delay: Duration::from_secs(5),
```
Comment (DonghunLouisLee) [inline src/connection_manager.rs:67]: from_millis(500) is 500 ms which is 0.5 second or do you intend to increase the default retry delay?

**Review by DonghunLouisLee — APPROVED** [review]
Logic sounds solid to me. I'll go ahead and merge this PR after you review the comments!

File: src/connection_manager.rs (hunk 5 above)
Comment (KannarFr) [reply src/connection_manager.rs:67]: Yes, I wanted to increase the default delay.

File: src/connection.rs (hunk 3 above)
Comment (KannarFr) [reply src/connection.rs]: Let's use UUID

File: src/connection.rs (hunk 4 above)
Comment (KannarFr) [reply src/connection.rs]: Let's use UUID

File: src/client.rs (hunk 2 above)
Comment (KannarFr) [reply src/client.rs]: Correct.

**Comment by KannarFr** [comment]
> Logic sounds solid to me. I'll go ahead and merge this PR after you review the comments!

@DonghunLouisLee bumped

File: src/producer.rs (hunk 1 above)
Comment (KannarFr) [reply src/producer.rs]: @FlorentinDUBOIS can you resolve this if it's okay for you?
